"""Render decision memo from pipeline outputs."""
from __future__ import annotations

from pathlib import Path

import pandas as pd


def render_decision_memo(
    kpis_csv: Path,
    cost_concentration_csv: Path,
    anomalies_csv: Path,
    *,
    output_path: Path,
) -> Path:
    """Render docs/decision_memo.md from pipeline outputs."""
    output_path.parent.mkdir(parents=True, exist_ok=True)

    kpis = pd.read_csv(kpis_csv)
    if kpis.empty:
        raise ValueError(f"KPIs CSV is empty: {kpis_csv}")

    row = kpis.iloc[0].to_dict()
    cost_conc = pd.read_csv(cost_concentration_csv)
    anomalies = pd.read_csv(anomalies_csv)

    # Extract KPI values
    total_billed = float(row.get("total_billed_amount", 0))
    avg_claim = float(row.get("avg_claim_amount", 0))
    unique_patients = int(row.get("unique_patients", 0))
    unique_diagnoses = int(row.get("unique_diagnoses", 0))
    top_dx = str(row.get("top_diagnosis_code", ""))
    top_dx_pct = float(row.get("top_diagnosis_pct_of_total", 0))
    pmpm = float(row.get("pmpm_billed", 0))
    anomaly_count = int(anomalies.shape[0])

    # Extract cost concentration
    top_1pct = cost_conc[cost_conc["top_pct_patients"] == 1]["cost_share_pct"].values
    top_5pct = cost_conc[cost_conc["top_pct_patients"] == 5]["cost_share_pct"].values
    top_10pct = cost_conc[cost_conc["top_pct_patients"] == 10]["cost_share_pct"].values

    top_1pct_val = float(top_1pct[0]) if len(top_1pct) > 0 else 0
    top_5pct_val = float(top_5pct[0]) if len(top_5pct) > 0 else 0
    top_10pct_val = float(top_10pct[0]) if len(top_10pct) > 0 else 0

    lines: list[str] = []
    lines.append("# Decision Memo: Healthcare Claims Analysis")
    lines.append("")
    lines.append("**Date**: Generated by pipeline (reproducible)")
    lines.append("")

    lines.append("## Goal")
    lines.append("")
    lines.append(
        "Analyze healthcare claims data to identify cost drivers, cost concentration patterns, and potential high-cost populations "
        "for targeted intervention."
    )
    lines.append("")

    lines.append("## Key Findings")
    lines.append("")
    lines.append(f"1. **Total billed amount**: ${total_billed:,.2f} across {unique_patients:,} patients in {int(row.get('row_count', 0)):,} claims.")
    lines.append(
        f"2. **Average claim**: ${avg_claim:.2f} (PMPM: ${pmpm:.2f}); " 
        f"diagnosis spectrum is broad ({unique_diagnoses} unique codes)."
    )
    lines.append(
        f"3. **Cost concentration**: Top 1% of patients account for {top_1pct_val:.1f}% of total cost; "
        f"top 10% account for {top_10pct_val:.1f}%."
    )
    lines.append(
        f"4. **Top diagnosis**: Code {top_dx} drives {top_dx_pct:.2f}% of total cost, indicating a key clinical driver."
    )
    lines.append(
        f"5. **Anomalies detected**: {anomaly_count} patients flagged as high-cost outliers (z-score ≥ 3.0)."
    )
    lines.append("")

    lines.append("## So What")
    lines.append("")
    lines.append(
        f"- **Pareto opportunity**: The top 10% of patients represent {top_10pct_val:.1f}% of spend; "
        "disease management or care coordination targeting this cohort could yield significant ROI."
    )
    lines.append(
        f"- **Clinical focus**: Diagnosis {top_dx} is a material cost driver; consider prevention/management programs "
        "to address this condition in the population."
    )
    lines.append("")

    lines.append("## Recommended Actions")
    lines.append("")
    lines.append(
        "1. **Segment patients** into utilization tiers (1%, 5%, 10%) and pilot targeted interventions (e.g., case management, "
        "preventive screenings) with the highest tier."
    )
    lines.append(
        f"2. **Focus on {top_dx} management**: Analyze root causes, develop educational materials, and measure improvement metrics "
        "(e.g., claim frequency, severity trend)."
    )
    lines.append(
        "3. **Establish dashboards** to monitor cost concentration, anomaly flags, and top diagnoses monthly; "
        "ensure action items are tracked and closed."
    )
    lines.append("")

    lines.append("## Limitations & Risks")
    lines.append("")
    lines.append(
        "- **Synthetic data**: This analysis uses synthetic healthcare claims; patterns may not reflect real-world distributions. "
        "Results should be validated against actual claims."
    )
    lines.append(
        "- **Temporal scope**: Analysis covers a fixed date range; seasonal or multi-year trends are not visible. "
        "Recommend rolling monthly re-analysis."
    )
    lines.append(
        "- **Missing context**: No clinical outcomes, member demographics, or provider performance data; "
        "insights are cost-centric only."
    )
    lines.append("")

    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return output_path


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--kpis", required=True, help="Path to kpis_summary.csv")
    parser.add_argument("--cost-concentration", required=True, help="Path to cost_concentration.csv")
    parser.add_argument("--anomalies", required=True, help="Path to patient_anomalies.csv")
    parser.add_argument("--output", required=True, help="Path to output decision_memo.md")
    args = parser.parse_args()

    render_decision_memo(
        Path(args.kpis),
        Path(args.cost_concentration),
        Path(args.anomalies),
        output_path=Path(args.output),
    )
    print(f"✓ Decision memo: {args.output}")
